package exams

import (
	"fmt"
	"math/rand"
)

// Question is the shape returned to the frontend for both AI-generated and
// offline-bank questions — matches server/ai.js / server/exams.js's output.
type Question struct {
	ID           string   `json:"id"`
	Domain       string   `json:"domain"`
	Scenario     string   `json:"scenario"`
	Question     string   `json:"question"`
	Options      []string `json:"options"`
	CorrectIndex int      `json:"correctIndex"`
	Explanation  string   `json:"explanation"`
}

// bankItem mirrors server/exams.js's QUESTION_BANK shorthand ({d,q,s,o,c,e}).
type bankItem struct {
	Domain       string
	Scenario     string
	Question     string
	Options      [4]string
	CorrectIndex int
	Explanation  string
}

var questionBank = map[string][]bankItem{
	"ccp": {
		{Domain: "Cloud Concepts", Question: "Which of the following best describes the main financial benefit of moving to the AWS cloud?", Options: [4]string{"Trading variable expense for fixed capital expense", "Trading capital expense for variable operating expense", "Eliminating all infrastructure costs entirely", "Locking in long-term hardware contracts at a discount"}, CorrectIndex: 1, Explanation: "The cloud replaces large upfront capital investments (buying servers) with pay-as-you-go variable costs that scale with actual usage."},
		{Domain: "Cloud Concepts", Question: "A company wants to run applications without managing servers, capacity or OS patching at all. Which cloud service model fits best?", Options: [4]string{"Infrastructure as a Service (IaaS)", "Platform/serverless offerings like AWS Lambda", "On-premises virtualization", "Colocation hosting"}, CorrectIndex: 1, Explanation: "Serverless/PaaS offerings such as Lambda remove server management entirely — AWS handles provisioning, scaling and patching."},
		{Domain: "Security & Compliance", Question: "Under the AWS Shared Responsibility Model, which task is the CUSTOMER responsible for?", Options: [4]string{"Physical security of data centers", "Patching the hypervisor", "Configuring security groups and IAM permissions", "Maintaining the global network infrastructure"}, CorrectIndex: 2, Explanation: "AWS secures the cloud itself (facilities, hardware, hypervisor); customers are responsible for security IN the cloud — their data, IAM, and network configuration."},
		{Domain: "Security & Compliance", Question: "What is the recommended way to grant an application running on an EC2 instance access to an S3 bucket?", Options: [4]string{"Store an IAM user access key in the application code", "Attach an IAM role to the EC2 instance", "Make the S3 bucket public", "Share the root account credentials with the application"}, CorrectIndex: 1, Explanation: "IAM roles provide temporary, automatically-rotated credentials to EC2 instances — no hardcoded keys, no long-lived secrets."},
		{Domain: "Cloud Technology & Services", Question: "Which AWS service is an object storage service designed for 99.999999999% (11 nines) durability?", Options: [4]string{"Amazon EBS", "Amazon S3", "Amazon RDS", "AWS Storage Gateway"}, CorrectIndex: 1, Explanation: "Amazon S3 is object storage with 11 nines of durability, achieved by redundantly storing objects across multiple devices and facilities."},
		{Domain: "Cloud Technology & Services", Question: "A team needs a managed relational database with automated backups and patching. Which service should they choose?", Options: [4]string{"Amazon DynamoDB", "Amazon RDS", "Amazon Redshift", "Amazon ElastiCache"}, CorrectIndex: 1, Explanation: "Amazon RDS is the managed relational database service (MySQL, PostgreSQL, etc.) handling backups, patching and failover. DynamoDB is NoSQL; Redshift is a data warehouse."},
		{Domain: "Cloud Technology & Services", Question: "Which service lets you run code in response to events without provisioning servers?", Options: [4]string{"Amazon EC2", "AWS Lambda", "Amazon Lightsail", "AWS Elastic Beanstalk"}, CorrectIndex: 1, Explanation: "AWS Lambda is event-driven, serverless compute — you upload code and pay only for execution time."},
		{Domain: "Billing, Pricing & Support", Question: "A workload runs 24/7 for the next 3 years with steady usage. Which EC2 pricing option is most cost-effective?", Options: [4]string{"On-Demand Instances", "Spot Instances", "Reserved Instances / Savings Plans", "Dedicated Hosts on demand"}, CorrectIndex: 2, Explanation: "Reserved Instances or Savings Plans give up to ~72% discount over On-Demand for steady, predictable long-term workloads. Spot is for interruptible workloads."},
		{Domain: "Billing, Pricing & Support", Question: "Which tool lets you set custom cost thresholds and receive alerts when spending exceeds them?", Options: [4]string{"AWS Cost Explorer", "AWS Budgets", "AWS Trusted Advisor", "AWS Organizations"}, CorrectIndex: 1, Explanation: "AWS Budgets lets you define cost or usage budgets and triggers alerts when actual or forecasted spend crosses thresholds. Cost Explorer is for analysis, not alerting."},
		{Domain: "Cloud Concepts", Question: "What does \"elasticity\" mean in cloud computing?", Options: [4]string{"The ability to recover quickly from failures", "The ability to automatically acquire and release resources to match demand", "Storing data across multiple regions", "Running workloads on physical servers you own"}, CorrectIndex: 1, Explanation: "Elasticity is scaling resources out and in automatically as demand changes — pay for what you need, when you need it. (Recovering from failures is resiliency.)"},
		{Domain: "Security & Compliance", Question: "Which service provides on-demand access to AWS compliance reports such as SOC and PCI?", Options: [4]string{"AWS Artifact", "AWS Shield", "Amazon Inspector", "AWS WAF"}, CorrectIndex: 0, Explanation: "AWS Artifact is the self-service portal for downloading AWS compliance and audit documents."},
		{Domain: "Billing, Pricing & Support", Question: "Which AWS Support plan is the minimum tier that includes a Technical Account Manager (TAM)?", Options: [4]string{"Developer", "Business", "Enterprise On-Ramp", "Enterprise"}, CorrectIndex: 3, Explanation: "A designated TAM is an Enterprise Support feature. Enterprise On-Ramp provides a pool of TAMs, but a designated TAM requires the full Enterprise plan."},
	},
	"saa": {
		{Domain: "Design Resilient Architectures", Scenario: "A web application runs on EC2 instances behind an Application Load Balancer in a single Availability Zone. Last month an AZ outage took the site down for four hours.", Question: "What should the architect do to improve availability with minimal redesign?", Options: [4]string{"Move the application to a single larger instance", "Distribute instances across multiple AZs in an Auto Scaling group behind the ALB", "Replicate the whole stack into another AWS account", "Switch the ALB to a Network Load Balancer"}, CorrectIndex: 1, Explanation: "Multi-AZ deployment with Auto Scaling is the standard pattern for high availability — the ALB health-checks and routes around a failed AZ automatically."},
		{Domain: "Design Resilient Architectures", Scenario: "An order-processing service writes directly to a downstream inventory API. During traffic spikes the inventory API gets overwhelmed and orders are lost.", Question: "Which change makes the system more resilient to these spikes?", Options: [4]string{"Increase the inventory API instance size", "Add retries with no backoff in the order service", "Decouple the services with an SQS queue between them", "Move both services to the same instance to reduce latency"}, CorrectIndex: 2, Explanation: "An SQS queue buffers bursts and decouples producers from consumers — the inventory service processes messages at its own pace and nothing is lost."},
		{Domain: "Design Secure Architectures", Scenario: "A company stores sensitive customer documents in S3. Compliance requires that all objects be encrypted at rest with keys the company can rotate and audit.", Question: "Which solution meets the requirement with the least operational overhead?", Options: [4]string{"SSE-S3 (Amazon-managed keys)", "SSE-KMS with a customer-managed KMS key", "Client-side encryption with keys on-premises", "Store documents unencrypted but block public access"}, CorrectIndex: 1, Explanation: "SSE-KMS with a customer-managed key gives audit trails via CloudTrail and key rotation control, while AWS still handles the heavy lifting."},
		{Domain: "Design Secure Architectures", Scenario: "An application tier on EC2 must connect to an RDS database. Security requires that only the application tier can reach the database on port 5432.", Question: "What is the best way to enforce this?", Options: [4]string{"Add a NACL rule allowing all VPC traffic to the DB subnet", "Reference the app tier's security group as the source in the DB security group inbound rule", "Use the same security group for every tier", "Allow 0.0.0.0/0 on port 5432 but enable SSL"}, CorrectIndex: 1, Explanation: "Security-group chaining (allowing inbound only from the app security group) restricts access to exactly the application tier, even as instances scale in and out."},
		{Domain: "Design High-Performing Architectures", Scenario: "A news site serves the same static images and articles to users worldwide. Users in Asia report slow load times; origin servers are in us-east-1.", Question: "Which solution improves global performance most directly?", Options: [4]string{"Add larger EC2 instances in us-east-1", "Serve content through Amazon CloudFront with the S3/ALB origin", "Move the database to DynamoDB", "Enable S3 Transfer Acceleration for end users"}, CorrectIndex: 1, Explanation: "CloudFront caches static content at edge locations near users worldwide, cutting latency dramatically for a read-heavy global site."},
		{Domain: "Design High-Performing Architectures", Scenario: "A read-heavy MySQL RDS database is hitting CPU limits because of repeated identical product-catalog queries.", Question: "Which combination best relieves the read pressure?", Options: [4]string{"Vertical scaling only — keep doubling the instance size", "Add read replicas and an ElastiCache caching layer", "Migrate to Redshift", "Enable Multi-AZ"}, CorrectIndex: 1, Explanation: "Read replicas spread read traffic and ElastiCache serves hot repeated queries from memory. Multi-AZ improves availability, not read performance."},
		{Domain: "Design Cost-Optimized Architectures", Scenario: "Application logs in S3 must be retained for 7 years for compliance. Logs older than 90 days are accessed at most once a year.", Question: "Which lifecycle strategy is most cost-effective?", Options: [4]string{"Keep everything in S3 Standard", "Transition objects to S3 Glacier Deep Archive after 90 days", "Delete logs after 90 days", "Copy old logs to EBS snapshots"}, CorrectIndex: 1, Explanation: "Glacier Deep Archive is the cheapest storage class, ideal for rarely-accessed compliance archives; a lifecycle rule automates the transition."},
		{Domain: "Design Cost-Optimized Architectures", Scenario: "A nightly batch job processes images for 3 hours and can tolerate interruptions and restarts.", Question: "Which compute option minimizes cost?", Options: [4]string{"On-Demand EC2 instances", "Reserved Instances", "Spot Instances", "Dedicated Hosts"}, CorrectIndex: 2, Explanation: "Spot Instances offer up to ~90% savings and are perfect for fault-tolerant, interruptible batch workloads."},
		{Domain: "Design Resilient Architectures", Scenario: "A company needs its RDS PostgreSQL database to fail over automatically within minutes if the primary instance or its AZ fails.", Question: "Which configuration provides this?", Options: [4]string{"Manual snapshots restored on failure", "RDS Multi-AZ deployment with a standby replica", "A read replica in the same AZ", "Daily automated backups"}, CorrectIndex: 1, Explanation: "Multi-AZ keeps a synchronous standby in another AZ and fails over automatically. Read replicas are asynchronous and need manual promotion."},
		{Domain: "Design Secure Architectures", Scenario: "EC2 instances in private subnets must download OS updates from the internet, but must not be reachable from the internet.", Question: "Which component enables this?", Options: [4]string{"An Internet Gateway with public IPs on the instances", "A NAT Gateway in a public subnet, with a route from the private subnets", "A VPC peering connection", "An ALB in front of the instances"}, CorrectIndex: 1, Explanation: "A NAT Gateway allows outbound-only internet access from private subnets — responses return, but no inbound connection can be initiated."},
		{Domain: "Design High-Performing Architectures", Scenario: "A gaming leaderboard needs single-digit-millisecond reads and writes at millions of requests per second, with a flexible schema.", Question: "Which database fits best?", Options: [4]string{"Amazon RDS MySQL", "Amazon DynamoDB", "Amazon Redshift", "Amazon Aurora PostgreSQL"}, CorrectIndex: 1, Explanation: "DynamoDB is built for massive-scale key-value workloads with consistent single-digit-millisecond latency."},
		{Domain: "Design Cost-Optimized Architectures", Scenario: "A startup runs a low-traffic API that is idle most of the day with occasional short bursts.", Question: "Which architecture minimizes cost for this pattern?", Options: [4]string{"Always-on EC2 instances behind an ALB", "API Gateway + AWS Lambda (pay per request)", "A dedicated RDS instance per endpoint", "An ECS cluster with reserved capacity"}, CorrectIndex: 1, Explanation: "With Lambda you pay only for actual invocations — an idle API costs nearly nothing, and bursts scale automatically."},
	},
	"devops": {
		{Domain: "CI/CD Pipelines", Scenario: "Your team merges to main several times a day. Production deploys are manual, happen weekly, and regularly break — rollbacks take an hour.", Question: "As the new DevOps engineer, what is the most impactful first improvement?", Options: [4]string{"Switch to deploying monthly to reduce risk", "Automate the pipeline: build, test and deploy on each merge with an automated rollback strategy", "Add a mandatory 3-day code freeze before each release", "Give every developer production access to fix issues faster"}, CorrectIndex: 1, Explanation: "Smaller, automated, frequent deployments with tests and fast rollback shrink both failure rate and recovery time — the core of CI/CD."},
		{Domain: "CI/CD Pipelines", Scenario: "A deployment needs zero downtime, and the business wants to test the new version on 5% of real traffic before full rollout.", Question: "Which release strategy fits?", Options: [4]string{"Recreate (stop old, start new)", "Blue/green with instant cutover", "Canary release", "Big-bang deployment at midnight"}, CorrectIndex: 2, Explanation: "A canary release routes a small slice of traffic to the new version, watches metrics, then gradually shifts the rest. Blue/green cuts over all traffic at once."},
		{Domain: "Containers & Docker", Scenario: "A Node.js app works on a developer laptop but crashes in production with \"module not found\". The Docker image is built from the project directory.", Question: "What is the most likely cause?", Options: [4]string{"Docker does not support Node.js", "node_modules was copied from the laptop instead of installed in the image, or a dependency is missing from package.json", "The container needs more CPU", "The image must be rebuilt on the production server"}, CorrectIndex: 1, Explanation: "Classic \"works on my machine\": dependencies must be declared in package.json and installed during the image build (with node_modules in .dockerignore) so the image is reproducible."},
		{Domain: "Containers & Docker", Scenario: "Your Docker image is 2.4 GB and pushes to the registry take ten minutes.", Question: "Which approach reduces the image size most effectively?", Options: [4]string{"Use a multi-stage build with a slim base image and copy only the build artifacts", "Run docker push with compression flags", "Combine the app and database into one container to save a pull", "Store images on a faster disk"}, CorrectIndex: 0, Explanation: "Multi-stage builds discard compilers and build tools — the final stage starts from a slim base (alpine/distroless) and contains only what runtime needs."},
		{Domain: "Infrastructure as Code", Scenario: "Someone changed a security group manually in the AWS console. Terraform plan now shows the resource will be modified back.", Question: "What is this situation called, and what is the right practice?", Options: [4]string{"State locking — delete the state file to fix it", "Configuration drift — apply changes only through code so infra matches the declared state", "A Terraform bug — upgrade the provider", "Race condition — run apply twice"}, CorrectIndex: 1, Explanation: "Manual console edits cause drift between real infrastructure and code. The fix is process: all changes go through code review and terraform apply."},
		{Domain: "Infrastructure as Code", Scenario: "Two engineers run terraform apply at the same time against the same state and corrupt it.", Question: "What prevents this?", Options: [4]string{"Asking in Slack before applying", "Remote state with state locking (e.g., S3 backend with locking)", "Keeping state files on each laptop", "Running apply only on Fridays"}, CorrectIndex: 1, Explanation: "A remote backend with state locking ensures only one apply mutates state at a time; the second run waits or fails cleanly."},
		{Domain: "Networking & Cloud", Scenario: "You are designing a VPC with CIDR 10.0.0.0/16 and need a subnet with roughly 250 usable addresses.", Question: "Which subnet size fits best?", Options: [4]string{"/28", "/26", "/24", "/16"}, CorrectIndex: 2, Explanation: "A /24 gives 256 addresses (251 usable on AWS after the 5 reserved). A /26 only gives 64; a /28 gives 16."},
		{Domain: "Networking & Cloud", Scenario: "Users report your site is unreachable, but the servers are healthy and serving traffic when hit by IP directly.", Question: "Which layer should you investigate first?", Options: [4]string{"Disk I/O on the servers", "DNS — records, TTLs and resolution", "The CPU governor settings", "Database indexes"}, CorrectIndex: 1, Explanation: "Reachable by IP but not by name points at DNS: expired/changed records, bad delegation or stale caches. Tools: dig, nslookup."},
		{Domain: "Monitoring & Incidents", Scenario: "At 2 AM, error rates spike on the checkout service. You are on call.", Question: "What is the best first move?", Options: [4]string{"Restart all services immediately", "Check dashboards/recent deploys to scope impact, and roll back the most recent change if it correlates", "Start refactoring the checkout code", "Wait 30 minutes to see if it self-heals"}, CorrectIndex: 1, Explanation: "Incident response starts with assessing scope and recent changes — a correlated rollback is usually the fastest mitigation. Fix forward later; postmortem after."},
		{Domain: "Monitoring & Incidents", Question: "What is the difference between metrics, logs and traces in observability?", Options: [4]string{"They are interchangeable names for log files", "Metrics are numeric time series, logs are discrete event records, traces follow a request across services", "Metrics are only for billing, logs for auditors, traces for developers", "Traces are aggregated metrics with timestamps"}, CorrectIndex: 1, Explanation: "The three pillars: metrics (aggregated numbers over time), logs (detailed event records), traces (the path and timing of a single request through distributed services)."},
		{Domain: "CI/CD Pipelines", Scenario: "Integration tests in the pipeline fail intermittently (~1 in 5 runs) with timeouts; devs have started clicking re-run until green.", Question: "What should you do about these flaky tests?", Options: [4]string{"Delete the integration tests", "Quarantine and fix the flaky tests — flakiness erodes trust and hides real failures", "Increase the retry count to 10", "Run tests only on release day"}, CorrectIndex: 1, Explanation: "Re-running until green trains the team to ignore failures. Track flaky tests, quarantine them out of the blocking path, and fix root causes (timing, shared state)."},
		{Domain: "Containers & Docker", Question: "Why should a container run a single main process rather than the app, database and cron jobs together?", Options: [4]string{"Docker enforces a one-process limit", "Separate containers scale, update and fail independently, with isolated logs and resources", "Multiple processes need a paid Docker license", "It only matters on Windows hosts"}, CorrectIndex: 1, Explanation: "One concern per container is the core of the container model: independent scaling, smaller images, cleaner failure domains and simpler orchestration."},
		{Domain: "Infrastructure as Code", Question: "What does \"terraform plan\" do?", Options: [4]string{"Immediately applies all pending changes", "Shows a preview diff of what would change without modifying anything", "Formats the configuration files", "Destroys unused resources"}, CorrectIndex: 1, Explanation: "plan compares desired state (code) with current state and prints the create/update/destroy diff — the review step before apply."},
		{Domain: "Networking & Cloud", Question: "What problem does a VPN solve when connecting an office network to a cloud VPC?", Options: [4]string{"It increases raw bandwidth between the sites", "It creates an encrypted tunnel over the public internet so private networks can talk securely", "It replaces the need for IP addressing", "It caches cloud content locally"}, CorrectIndex: 1, Explanation: "A site-to-site VPN encrypts traffic between the office gateway and the cloud VPN gateway, extending the private network securely across the public internet."},
	},
}

// SampleQuestions ports server/exams.js's sampleQuestions: a random subset
// (shuffle, then take min(count, len)) of the offline bank for examType.
func SampleQuestions(examType string, count int) []Question {
	bank := questionBank[examType]
	shuffled := make([]bankItem, len(bank))
	copy(shuffled, bank)
	rand.Shuffle(len(shuffled), func(i, j int) { shuffled[i], shuffled[j] = shuffled[j], shuffled[i] })

	n := count
	if n > len(shuffled) {
		n = len(shuffled)
	}
	out := make([]Question, n)
	for i, item := range shuffled[:n] {
		out[i] = Question{
			ID:           fmt.Sprintf("q%d", i+1),
			Domain:       item.Domain,
			Scenario:     item.Scenario,
			Question:     item.Question,
			Options:      item.Options[:],
			CorrectIndex: item.CorrectIndex,
			Explanation:  item.Explanation,
		}
	}
	return out
}
